import "./globals.css";
import { Antonio, Asap } from "next/font/google";
import SupabaseProvider from "./supabase-provider";

const asap = Asap({
	subsets: ["latin"],
	variable: "--font-asap",
});

const antonio = Antonio({
	subsets: ["latin"],
	variable: "--font-antonio",
});

export const metadata = {
	title: "Inclusieweb",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={`${asap.variable} ${antonio.variable}`}>
			<body>
				<SupabaseProvider>{children}</SupabaseProvider>
			</body>
		</html>
	);
}
