import './globals.css';
import { Antonio, Asap } from 'next/font/google';

const asap = Asap({
    subsets: ['latin'],
    variable: '--font-asap',
})

const antonio = Antonio({
    subsets: ['latin'],
    variable: '--font-antonio',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${asap.variable} font-asap ${antonio.variable} antonio`}>
                {children}
            </body>
        </html>
    )
}
